name: Build main

on:
  push:
    branches:
    - '*'


jobs:
  build:
    name: Build container image
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: docker build .